previewsEnabled: false

databases:
  - name: lightdash-database
    databaseName: lightdash_database_dms
    user: lightdash_database_dms_user
    plan: starter
    region: frankfurt
    ipAllowList: [ ]

services:
  - type: web
    name: lightdash-server
    runtime: docker
    repo: https://github.com/dataly-agency/lightdash-render-template
    plan: standard
    envVars:
      - key: LIGHTDASH_SECRET
        generateValue: true
      - key: SECURE_COOKIES
        value: true
      - key: TRUST_PROXY
        value: true
      - key: PGPASSWORD
        fromDatabase:
          name: lightdash-database
          property: password
      - key: PGUSER
        fromDatabase:
          name: lightdash-database
          property: user
      - key: PGDATABASE
        fromDatabase:
          name: lightdash-database
          property: database
      - key: PGPORT
        fromDatabase:
          name: lightdash-database
          property: port
      - key: PGHOST
        fromDatabase:
          name: lightdash-database
          property: host
    region: frankfurt
    dockerContext: .
    dockerfilePath: dockerfile
    domains:
      - lightdash.deserved.cz
