previewsEnabled: false

databases:
  - name: lightdash-database
    ipAllowList: [ ]
    plan: starter
    region: frankfurt

services:
  - type: web
    name: lightdash-server
    runtime: docker
    dockerContext: .
    dockerfilePath: dockerfile
    plan: standard
    region: frankfurt
    envVars:
      - key: PGHOST
        fromDatabase:
          name: lightdash-database
          property: host
      - key: PGPORT
        fromDatabase:
          name: lightdash-database
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: lightdash-database
          property: database
      - key: PGUSER
        fromDatabase:
          name: lightdash-database
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: lightdash-database
          property: password
      - key: TRUST_PROXY
        value: true
      - key: SECURE_COOKIES
        value: true
      - key: LIGHTDASH_SECRET
        generateValue: true

